services:
  - type: web
    name: vehicles-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_PORT_NUMBER
        value: 3000
      - key: JWT_SECRET
        sync: false
      - key: REFRESH_SECRET
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306